# Generated by Django 4.2.6 on 2023-11-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ID', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_unit', models.CharField(max_length=50)),
                ('p_normalRange', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.group')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('tel_num', models.CharField(max_length=15)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], default='Pending', max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.group')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_ID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('p_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.parameters')),
                ('sample_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.sample')),
            ],
        ),
    ]
