# Generated by Django 4.2.6 on 2023-11-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='gen',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('p_name', 'gen')},
        ),
    ]
