# Generated by Django 4.2.6 on 2023-11-24 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_parameters_gen_alter_patient_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
