# Generated by Django 4.2.6 on 2023-11-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_alter_sample_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], default='P', max_length=1),
        ),
    ]
