FROM python:3.12-slim
# create a dir 
WORKDIR /model 
# copy all files required into the new dir
COPY requirements.txt /model/
COPY main.py /model/
COPY KNN_model.pkl /model/
COPY scaler.pkl /model/

# install the requirements
RUN pip install --no-cache-dir -r requirements.txt
# rub FASTAPI server on port 8443
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8443"]